# Generated by Django 3.1.1 on 2020-09-24 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgasCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(default='unknown')),
                ('code', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CovidData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ministry_id', models.IntegerField()),
                ('date', models.DateField()),
                ('accumulated_tested', models.IntegerField(default=-1)),
                ('new_tested_on_date', models.BooleanField()),
                ('accumulated_cases', models.IntegerField(default=-1)),
                ('new_cases_on_date', models.BooleanField()),
                ('accumulated_recoveries', models.IntegerField(default=-1)),
                ('new_recoveries_on_date', models.BooleanField()),
                ('accumulated_hospitalized', models.IntegerField(default=-1)),
                ('new_hospitalized_on_date', models.BooleanField()),
                ('accumulated_deaths', models.IntegerField(default=-1)),
                ('new_deaths_on_date', models.BooleanField()),
                ('agas_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_data.agascity')),
            ],
        ),
        migrations.AddField(
            model_name='agascity',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_data.city'),
        ),
    ]
