# Generated by Django 3.1.1 on 2020-09-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agascity',
            name='name',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
