# Generated by Django 3.1.1 on 2020-09-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_data', '0002_auto_20200924_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agascity',
            old_name='name',
            new_name='districts',
        ),
        migrations.AddField(
            model_name='agascity',
            name='main_streets',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
