# Generated by Django 3.1.1 on 2020-09-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_data', '0003_auto_20200925_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='code',
            field=models.SmallIntegerField(unique=True),
        ),
    ]
