# Generated by Django 3.1.1 on 2020-10-17 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_data', '0004_auto_20200925_1048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coviddata',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='agascity',
            name='districts',
            field=models.CharField(default='unknown', max_length=300),
        ),
        migrations.CreateModel(
            name='CityData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ministry_id', models.IntegerField()),
                ('date', models.DateField()),
                ('cumulative_verified_cases', models.IntegerField()),
                ('cumulated_recovered', models.IntegerField()),
                ('cumulated_deaths', models.IntegerField()),
                ('cumulated_number_of_tests', models.IntegerField()),
                ('cumulated_number_of_diagnostic_tests', models.IntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_data.city')),
            ],
        ),
    ]
